using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortalHub.Produtos
{
    public class ProdutoManager : ProdutoManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProdutoManager(IProdutoRepository produtoRepository)
            : base(produtoRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}