using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace PortalHub.CategoriaProdutos
{
    public class CategoriaProduto : CategoriaProdutoBase
    {
        //<suite-custom-code-autogenerated>
        protected CategoriaProduto()
        {

        }

        public CategoriaProduto(Guid id, string nome, string? descricao = null)
            : base(id, nome, descricao)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}