using PortalHub.Produtos;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace PortalHub.CategoriaProdutos
{
    public class CategoriaProdutoManager : CategoriaProdutoManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CategoriaProdutoManager(ICategoriaProdutoRepository categoriaProdutoRepository,
        IRepository<Produto, Guid> produtoRepository)
            : base(categoriaProdutoRepository, produtoRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}