using PortalHub.Shared;
using PortalHub.Produtos;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortalHub.Permissions;
using PortalHub.CategoriaProdutos;

namespace PortalHub.CategoriaProdutos
{
    public class CategoriaProdutosAppService : CategoriaProdutosAppServiceBase, ICategoriaProdutosAppService
    {
        //<suite-custom-code-autogenerated>
        public CategoriaProdutosAppService(ICategoriaProdutoRepository categoriaProdutoRepository, CategoriaProdutoManager categoriaProdutoManager, IRepository<PortalHub.Produtos.Produto, Guid> produtoRepository)
            : base(categoriaProdutoRepository, categoriaProdutoManager, produtoRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}