using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using PortalHub.Permissions;
using PortalHub.Produtos;

namespace PortalHub.Produtos
{
    public class ProdutosAppService : ProdutosAppServiceBase, IProdutosAppService
    {
        //<suite-custom-code-autogenerated>
        public ProdutosAppService(IProdutoRepository produtoRepository, ProdutoManager produtoManager)
            : base(produtoRepository, produtoManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}